// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdn4Y-zzM4czP6OycJ9o2Jp_mDXqcFTOo',
    appId: '1:659929800170:web:fbe603bf04a626ba0aa693',
    messagingSenderId: '659929800170',
    projectId: 'mad3-firebase-auth',
    authDomain: 'mad3-firebase-auth.firebaseapp.com',
    storageBucket: 'mad3-firebase-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmL2ZvKnPu9SpQLstppfOglGlZNr7jcf0',
    appId: '1:659929800170:android:27ec02f7af0259fb0aa693',
    messagingSenderId: '659929800170',
    projectId: 'mad3-firebase-auth',
    storageBucket: 'mad3-firebase-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNKUn6fwFr-OGmuC6rNSU5XpXiMuBEAlw',
    appId: '1:659929800170:ios:f2b95feff31990d50aa693',
    messagingSenderId: '659929800170',
    projectId: 'mad3-firebase-auth',
    storageBucket: 'mad3-firebase-auth.appspot.com',
    iosBundleId: 'com.example.stateChangeDemo',
  );
}
